<?php

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function players_cfg_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
//  $form['name']['#title'] = t('Email address');
//  $form['name']['#description'] = t('Enter your email address.');
//  $form['pass']['#description'] = t('Enter your Player\'s Inc password.');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function players_cfg_form_user_pass_alter(&$form, FormStateInterface $form_state, $form_id) {
//  $form['name']['#title'] = t('Email address');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function players_cfg_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {
//  $form['account']['name']['#required'] = FALSE;
//  $form['#validate'] = [];
}

/**
 * Implements hook_entity_presave().
 */
function players_cfg_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  
}
